export const TASKS_FETCH = 'TASKS_FETCH';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_ERROR = 'TASKS_ERROR';

export const NEXT_TASKS_FETCH = 'NEXT_TASKS_FETCH';
export const NEXT_TASKS_SUCCESS = 'NEXT_TASKS_SUCCESS';
export const NEXT_TASKS_ERROR = 'NEXT_TASKS_ERROR';
