export const AGENTS_FETCH = 'AGENTS_FETCH';
export const AGENTS_SUCCESS = 'AGENTS_SUCCESS';
export const AGENTS_ERROR = 'AGENTS_ERROR';

export const AGENT_USERS_FETCH = 'AGENT_USERS_FETCH';
export const AGENT_USERS_SUCCESS = 'AGENT_USERS_SUCCESS';
export const AGENT_USERS_ERROR = 'AGENT_USERS_ERROR';