export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const KEYCLOAK_INIT_FETCH = 'KEYCLOAK_INIT_FETCH';
export const KEYCLOAK_INIT_SUCCESS = 'KEYCLOAK_INIT_SUCCESS';
export const KEYCLOAK_INIT_ERROR = 'KEYCLOAK_INIT_ERROR';
